name: "🌎 환경설정"
description: "환경설정에 대한 보고서입니다"
title: "🌎 "
labels: ["🌎 환경설정"]
projects: []
assignees:
  - kyoulee
body:
  - type: markdown
    attributes:
      value: |
        # 환경설정 보고서

        개발 환경에 맞는 환경을 설정하기위한 보고서입니다

        정해진 환경에 알맞게 설정하고 모든이가 공통작업을 할 수 있도록 만드는것이 목표입니다

        ## 환경설정 작성 방법
          - 다음줄에 기입이 가능하며
          - 깃 허브 마크다운으로 작동합니다
  - type: input
    id: input_name
    attributes:
      label: 📣 환경설정 이름
      description: 💭 환경설정의 이름을 작성해 주세요
      placeholder: 🫧 <이름>
    validations:
      required: true
  - type: textarea
    id: textarea_description
    attributes:
      label: 📣 환경설정 필요 목록
      description: 💭 환경설정 필요 목록을 적어주세요
      placeholder: |
        🫧 <환경설정 필요 목록>
        1. <목록 1>
        2. <목록 2>
      render: ''
    validations:
      required: true
  - type: textarea
    id: textarea_work
    attributes:
      label: ✅ 환경설정 리스트
      description: 💭 작업에 필요한 환경구현
      placeholder: |
        🫧 <ex. 예시 지문>
        - [ ] <체크 1>
        - [ ] <체크 2>
      value: |
        - [ ] 프론트엔드 프레임워크
        - [ ] 백엔드 프레임워크
        - [ ] 클라우드 환경설정
        - [ ] <# github 이슈> github 환경설정
        - [ ] 프로젝트 환경설정
        - [ ] 커뮤니티 활성화
        - [ ] DNS 설정
        - [ ] 공통작업 방법 설명서 작성
      render: ''
    validations:
      required: true
  - type: checkboxes
    id: checkboxes_list
    attributes:
      label: 📣 작성자 체크리스트
      description: 💭 작성자 체크리스트
      options:
        - label: 🔱 환경설정 제목을 적절하게 정하였습니까?
          required: false
        - label: 🔱 환경설정 리스트를 이슈에 맞게 설정하셨습니까?
          required: false
        - label: 📍 타이틀에 환경설정 이름을 추가하였습니까?
          required: true
        - label: 📌 작성자는 모든 작업에 대한 정보가 공개됨을 동의함니까?
          required: true
