name: master just dev

on:
  pull_request:
    branches: [ master ]

jobs:
  check-master:
    runs-on: ubuntu-latest
    steps:
      - name: master just dev
        run: |
          if [[ "$GITHUB_HEAD_REF" != 'dev' ]]; then exit 1; else exit 0; fi;
